// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace API.ProductionControl.Models;

public partial class OrderNumberOnDate
{
    public int Id { get; set; }

    public int YearValue { get; set; }

    public int MonthValue { get; set; }

    public int OrderNumber { get; set; }
}