//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionControl {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.168.104:18012")]
        public string RAY_API {
            get {
                return ((string)(this["RAY_API"]));
            }
            set {
                this["RAY_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = 192.168.168.104; Initial Catalog = VKT; Persist Security Info = Tru" +
            "e; User ID = Apps; Password = 793148625; Application Name = ProductionControl; C" +
            "onnect Timeout=60")]
        public string ConVKT {
            get {
                return ((string)(this["ConVKT"]));
            }
            set {
                this["ConVKT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.168.104")]
        public string VKT_API {
            get {
                return ((string)(this["VKT_API"]));
            }
            set {
                this["VKT_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = SERVER-TO1; Initial Catalog = Test; Persist Security Info = True; U" +
            "ser ID = Apps; Password = 793148625; \tApplication Name = ProductionControl; Trus" +
            "tServerCertificate=True")]
        public string ConTest {
            get {
                return ((string)(this["ConTest"]));
            }
            set {
                this["ConTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data source = SERVER-BD2; User Id = to; Password = toto; Initial Catalog = rvp002" +
            "; Application Name = ProductionControl; Connect Timeout=60")]
        public string ConBest {
            get {
                return ((string)(this["ConBest"]));
            }
            set {
                this["ConBest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = SERVER-TO1; Initial Catalog = TimeSheet; Persist Security Info = Tr" +
            "ue; User ID = Apps; Password = 793148625; \tApplication Name = ProductionControl;" +
            " TrustServerCertificate=True; Connect Timeout=60")]
        public string ConTimeSheet {
            get {
                return ((string)(this["ConTimeSheet"]));
            }
            set {
                this["ConTimeSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source = SERVER-TO1; Initial Catalog = Test_TimeSheet; Persist Security Info" +
            " = True; User ID = Apps; Password = 793148625; \tApplication Name = ProductionCon" +
            "trol; TrustServerCertificate=True")]
        public string TestTimeSheet {
            get {
                return ((string)(this["TestTimeSheet"]));
            }
            set {
                this["TestTimeSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://server-to1:31514")]
        public string Prodaction_API {
            get {
                return ((string)(this["Prodaction_API"]));
            }
            set {
                this["Prodaction_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5044")]
        public string Test_Prodaction_API {
            get {
                return ((string)(this["Test_Prodaction_API"]));
            }
            set {
                this["Test_Prodaction_API"] = value;
            }
        }
    }
}
