//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionControl {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=RYZEN; Initial Catalog = TimeSheet; Database=TimeSheet; Trusted_Connection" +
            "=True;  TrustServerCertificate=True; Encrypt=False; Application Name = Productio" +
            "nControl; ")]
        public string ConTimeSheet {
            get {
                return ((string)(this["ConTimeSheet"]));
            }
            set {
                this["ConTimeSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=ACER\\SQLEXPRESS; Initial Catalog = TimeSheet; Database=TimeSheet; Trusted_" +
            "Connection=True;  TrustServerCertificate=True; Encrypt=False; Application Name =" +
            " ProductionControl; ")]
        public string ConTimeSheetN {
            get {
                return ((string)(this["ConTimeSheetN"]));
            }
            set {
                this["ConTimeSheetN"] = value;
            }
        }
    }
}
